# default:
#   image: docker:cli
#   services:
#     - docker:dind
#   before_script:
#     - apk add curl bash
#     - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
#     - cp .secure_files/.env.production .env
#     - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY

# variables:
#   TAG_BASE: $REGISTRY/$REGISTRY_NAME/

# keystone:
#   variables:
#     TAG: $TAG_BASE$CI_JOB_NAME
#   script:
#     - docker build
#       --pull -t $TAG .
#     - docker push $TAG
#   rules:
#     - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH

# prisma-migrate:
#   variables:
#     TAG: $TAG_BASE$CI_JOB_NAME
#   script:
#     - docker build
#       --pull -f DockerfileMigrate -t $TAG .
#     - docker push $TAG
#   rules:
#     - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH
